// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {log} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetLogs():Promise<Array<log.LogEntry>>;

export function GetStatus():Promise<string>;

export function IsAutoStartEnabled():Promise<boolean>;

export function Start():Promise<void>;

export function Stop():Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;
