// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {log} from '../models';
import {recorder} from '../models';

export function ClearRecording():Promise<void>;

export function DeleteRecording(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetLogs():Promise<Array<log.LogEntry>>;

export function GetRecording():Promise<recorder.Recording>;

export function GetRecordingStatus():Promise<recorder.RecorderStatusInfo>;

export function GetStatus():Promise<string>;

export function IsAutoStartEnabled():Promise<boolean>;

export function ListRecordings():Promise<Array<string>>;

export function LoadRecording(arg1:string):Promise<recorder.Recording>;

export function Pause():Promise<void>;

export function Resume():Promise<void>;

export function SaveRecording(arg1:string):Promise<void>;

export function Start():Promise<void>;

export function StartRecording():Promise<void>;

export function Stop():Promise<void>;

export function StopRecording():Promise<recorder.Recording>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function UpdateHotkeys(arg1:config.HotkeyConfig):Promise<void>;
