// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRecording() {
  return window['go']['main']['App']['ClearRecording']();
}

export function DeleteRecording(arg1) {
  return window['go']['main']['App']['DeleteRecording'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetRecording() {
  return window['go']['main']['App']['GetRecording']();
}

export function GetRecordingStatus() {
  return window['go']['main']['App']['GetRecordingStatus']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsAutoStartEnabled() {
  return window['go']['main']['App']['IsAutoStartEnabled']();
}

export function ListRecordings() {
  return window['go']['main']['App']['ListRecordings']();
}

export function LoadRecording(arg1) {
  return window['go']['main']['App']['LoadRecording'](arg1);
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function SaveRecording(arg1) {
  return window['go']['main']['App']['SaveRecording'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateHotkeys(arg1) {
  return window['go']['main']['App']['UpdateHotkeys'](arg1);
}
